# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f7eb268b5c74cfd6eb7b37041faef033e39a8db5421181f87ef3320c5bd7ed234c1258c7565d20439eceb30e0d1d11d8b3e77f1ec68e2712f0221ec2b5de84

test:
  secret_key_base: 8dae3a6ab793babc0faf00ab49ed3931d43d0c64e44f9761a72d66de9a932e748a15c437a5faa008a8c1805128ff2ff475d8a83dae81d7abb658b603fbcd6ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
